import Head from "next/head";
import React from "react"

interface IPropsLayoutDefault {
    titlePage: string
    children: any
}

class LayoutDefault extends React.Component<IPropsLayoutDefault> {

    constructor(props: IPropsLayoutDefault) {
        super(props);
    }

    render(): React.ReactNode {
        const { children, titlePage } = this.props;
        return (
            <>
                <Head>
                    <title>{titlePage ?? "Create Next App"}</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <main>
                    {children}
                </main>
            </>

        )
    }
}

export default LayoutDefault;